### PR TITLE
Update dependancies

### PR DESCRIPTION
**Pull request by ionab**
This PR updates outdated dependancies within the application.
Key update 

-  Gatsby version update from 2 -> 4 and associated breaking changes fixed

### CODE REVIEW

**Review by Heather0K — APPROVED** [review]

**Review by sammeltassen — CHANGES_REQUESTED** [review]
Collections work! Two more things I missed earlier:
* The relationships between items and publications seem broken. For example [this object](https://deploy-preview-114--delft-static-site-generator.netlify.app/en/objects/ex-na-4.KIVI-864-899/?id=0) is used in [this](https://deploy-preview-114--delft-static-site-generator.netlify.app/en/publications/tu-itb) article (but no referrals)
* Correct ids are missing from links in exhibitions to objects, for example the [book pages here](https://deploy-preview-114--delft-static-site-generator.netlify.app/en/exhibitions/novieten)

**Comment by ionab** [comment]
@sammeltassen I think I've captured those bugs now, good spot.

**Review by sammeltassen — CHANGES_REQUESTED** [review]
Thanks @ionab! One more thing: could you also restore the 'backlink' from the object page to the publication(s), see eg. [this object](https://deploy-preview-114--delft-static-site-generator.netlify.app/en/objects/ex-na-4.KIVI-864-899/?id=0), which is used in [this article](https://deploy-preview-114--delft-static-site-generator.netlify.app/en/publications/tu-itb).

**Review by Heather0K — APPROVED** [review]
Looks good!

**Review by sammeltassen — APPROVED** [review]

**Pull request merged**
